package com.dmc.jsoup;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 * @Author:dingmc
 * @Description:
 * @Date: Created in 11:23 AM 2019/4/26
 * @Modified By:
 */
public class test5 {

    public static void main(String[] args) {
        String str = "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>170908224205131</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>180726011029757</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190226114827383</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190226143736434</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190226194745490</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190301145304897</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190301120709845</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190303194004201</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>1704131420151209</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>170615102331400</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>181019105859995</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190307093522702</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190309024500985</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190312093309157</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190312185655258</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190309024500985</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190313103101319</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190128185724738</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190314102830489</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190314131310498</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190314154846529</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190315121037644</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190315162749713</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190316120501791</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>170511184904349</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>180624092052666</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>181228161140353</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190318153954102</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190318174549129</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190109170040694</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190319051839160</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190319091645161</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>170627123142653</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190319231342306</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190320143913389</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190320151141386</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190321145112535</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190321153117551</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190322164747734</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190323124506811</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190323162529828</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190325124656978</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>180702113731570</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190301180520941</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190313091644304</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190327104105409</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190325114752961</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190327171435499</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>161121192746371</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>171028233827835</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190328182831715</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190328225205742</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190329114417782</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190329153932826</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190329165937847</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190330180554974</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190325124656978</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190331213600157</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190401141156213</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190328235036731</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190317230911919</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>170525112154340</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>180727164422259</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190403172150645</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190403234314698</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190404044345701</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190328161148661</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190404143139760</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190404151617780</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190404161759796</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190404164119801</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190406162912975</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190406195229987</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190406212856989</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190407122914112</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190407162451136</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190407193711160</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190403105158539</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>161013191156211</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190408193333340</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190408203535312</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190409105421360</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190409113107367</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190409104012382</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>181004231829531</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>171023153915409</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>180707135235317</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190327044006379</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>160313202214172</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190410030027570</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>180930212914196</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>161222175821325</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190410111754607</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190409113107367</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190409113107367</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>160618162809228</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190410161413675</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>161209104825156</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190410181555706</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>180607201419182</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190411130755787</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190411150158835</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190121165634233</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190121165634233</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190412044247932</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190412121431934</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190412132400975</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190412143302103</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>160316141510131</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190413023958214</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190413120556246</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>160310121638168</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190412044247932</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190412044247932</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190412044247932</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>180511175558258</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190414112730303</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190414132240350</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190412044247932</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190414144737328</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190415092507441</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190415092507441</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190415092507441</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190415164358529</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190415092507441</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190415092507441</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190415092507441</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>180502162333524</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190316120501791</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190416115216611</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190222134522854</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190410081317573</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190410081317573</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190417091421722</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>160812100927131</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190408203535312</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190417121159791</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190417121159791</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190417123745798</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>181019065556214</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190417165807856</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>170514131535487</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190418021200914</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>181018110253873</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>181120171645238</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>170522150700478</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190418175141112</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190418181725980</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190418213807105</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190419092314124</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>180511175558258</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190411130755787</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190417223036898</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190419192444246</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190420113942321</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190412122140938</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190421174535439</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190422012218492</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190422090410503</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190122191843257</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190423122202225</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190423154812256</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190228162447742</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>181023092051514</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>170228011751334</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190424090337347</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190415092507441</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190422210800138</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190415092507441</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190424144911414</span> <!----> <!----></div></td></tr> <!----></tbody>\n"
            + "\n"
            + "<tbody class=\"ivu-table-tbody\"><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>161217121102155</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190425143002520</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190425155641565</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190425160217545</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>190425162904575</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>171204170303803</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>171206193851146</span> <!----> <!----></div></td></tr> <!----><tr class=\"ivu-table-row\"><td class=\"\"><div class=\"ivu-table-cell\"><!----> <!----> <!----> <span>160621183905225</span> <!----> <!----></div></td></tr> <!----></tbody>";

        final String url = "curl 'http://localhost:8010/command/evaluateSeller/add-by-clientId?platform=SELF_DEVELOP&clientId={clientId}';";
        Document doc = Jsoup.parse(str);
        Elements elements = doc.getElementsByTag("span");
        for (int i = 0;i < elements.size(); i++) {
//            System.out.println(elements.get(i).text());
            String z = url;
            System.out.print(z.replace("{clientId}", elements.get(i).text()));
            if (i != 0 && i % 20 == 0) {
                System.out.println();
            }
        }
    }
}
